boilerplate=true
all=true
project="The Boolean Home Automation Lua Library"
sort=false
dir="../Docs/"
full_description="This module attempts to provide functions that solve common problems in home automation tasks within the scriptiong library supplied by Fibaro Home Center 2. The aim is to afford the construction of easilly readable code in scenes that may hten be easilly maintained. The Makefile concatenates all Lua code files in the library into a single file and preprocesses it so that the contents of the resulting file 'lib/fk_lib.lua' may be inserted as is into a scene, and then all the functionality of the library may be used."
